[phases.setup]
nixPkgs = ['...']


[phases.install]
# ...

[phases.build]
cmds = [
    "cargo build --release --target x86_64-unknown-linux-musl", 
]

[start]
cmd = "./target/x86_64-unknown-linux-musl/release/app_backend"